version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_lumi
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lumi
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: nestjs_lumi
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/lumi?schema=public'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
